[cli] Setup Unistyles theme
danstepanov/create-expo-stack pull request #189
Opened 2024-01-25 09:36 UTC by coyksdev

## Description

- Add components to the unistyles theme that can be reused by each template
- Add missing unistyles registry import

2024-01-25 22:14 UTC, danstepanov commented on cli/src/templates/packages/expo-router/drawer/app/(drawer)/index.tsx.ejs
> +    const {theme} = useStyles()
```suggestion
    const { theme } = useStyles()
```

2024-01-25 22:15 UTC, danstepanov commented on cli/src/templates/packages/expo-router/drawer/app/(drawer)/news.tsx.ejs
> +    const {theme} = useStyles();
```suggestion
    const { theme } = useStyles();
```

2024-01-25 22:16 UTC, danstepanov commented on cli/src/templates/packages/expo-router/stack/app/details.tsx.ejs
> +    const {styles, theme} = useStyles(stylesheet);
```suggestion
    const { styles, theme } = useStyles(stylesheet);
```

2024-01-25 22:18 UTC, danstepanov commented on cli/src/templates/packages/expo-router/stack/app/details.tsx.ejs
> +		);
```suggestion
    const BackButton = () => (
			<TouchableOpacity onPress={router.back}>
			  <View style={styles.backButton}>
				  <Feather name="chevron-left" size={16} color={theme.colors.azureRadiance} />
				  <Text style={styles.backButtonText}>Back</Text>
			  </View>
			</TouchableOpacity>
		);
```

2024-01-25 22:19 UTC, danstepanov commented on cli/src/templates/packages/expo-router/stack/app/index.tsx.ejs
> +    const {styles, theme} = useStyles(stylesheet);
```suggestion
    const { styles, theme } = useStyles(stylesheet);
```

2024-01-25 22:24 UTC, danstepanov commented on cli/src/templates/packages/expo-router/stack/app/index.tsx.ejs
> +			</View>
```suggestion
    <% } else if (props.stylingPackage?.name === "unistyles") { %>
      <View style={styles.container}>
				<View style={styles.main}>
          <Stack.Screen options={{ title: "Overview" }} />
				  <View>
					  <Text style={theme.components.title}>Hello World</Text>
					  <Text style={theme.components.subtitle}>This is the first page of your app.</Text>
				  </View>
				  <Link href={{ pathname: "/details", params: { name: "Dan" } }} asChild>
					  <TouchableOpacity style={theme.components.button} >
					    <Text style={theme.components.buttonText}>Show Details</Text>
					  </TouchableOpacity>
				  </Link>
				</View>
			</View>
```

2024-01-25 22:26 UTC, danstepanov requested changes
Few syntax changes

2024-01-25 23:32 UTC, ludwig-pro approved these changes
Great job! It's "DRY"! +253 −330

Just a suggestion: sometimes you are using single quotes ' and other times double quotes ". I guess single quotes are the way to follow according to the prettier.rc config

2024-01-26 00:22 UTC, danstepanov commented
> Great job! It's "DRY"! +253 −330
> 
> Just a suggestion: sometimes you are using single quotes ' and other times double quotes ". I guess single quotes are the way to follow according to the prettier.rc config

yea please change all uses of double quotes to single quotes

2024-01-26 00:58 UTC, coyksdev commented
> > Great job! It's "DRY"! +253 −330
> > Just a suggestion: sometimes you are using single quotes ' and other times double quotes ". I guess single quotes are the way to follow according to the prettier.rc config
> 
> yea please change all uses of double quotes to single quotes

@danstepanov would you think I create a separate PR for this? I will apply it to all of the templates

2024-01-26 02:31 UTC, danstepanov commented
> > > Great job! It's "DRY"! +253 −330
> > > Just a suggestion: sometimes you are using single quotes ' and other times double quotes ". I guess single quotes are the way to follow according to the prettier.rc config
> > 
> > 
> > yea please change all uses of double quotes to single quotes
> 
> @danstepanov would you think I create a separate PR for this? I will apply it to all of the templates

just apply it to the files in your PR and address the above changes that I highlighted, no need for another PR

2024-01-26 02:45 UTC, coyksdev commented
@danstepanov @ludwig-pro requested changes applied

2024-01-26 03:20 UTC, danstepanov approved these changes
LGTM

2024-01-26 03:20 UTC, merged