Setting up Prompts for release workflow
danstepanov/create-expo-stack pull request #29
Opened 2023-10-22 08:49 UTC by agrittiwari

Working on setting up EAS for the first iteration, then will work on codepush

2023-10-22 17:15 UTC, agrittiwari commented
@danstepanov lmk wdyt

2023-10-23 19:40 UTC, danstepanov commented
@agrittiwari what is the specific feedback you're asking for? Also can you indicate which changes pertain to your PR vs just the formatting stuff?

2023-10-26 11:07 UTC, agrittiwari commented
@danstepanov  Need some review on the PR, specifically regarding this, "should I ask for project Id in prompt or left an info in cli saying, " update, projectId in app.json`

2023-10-26 11:23 UTC, agrittiwari commented
> @agrittiwari what is the specific feedback you're asking for? Also can you indicate which changes pertain to your PR vs just the formatting stuff?

II want to know how to remove the formatting related changes from the PR!!!

2023-11-06 06:04 UTC, danstepanov requested changes
I'm not sure this will work if the user chooses Expo Router as `App.tsx` doesn't exist for Expo Router. Can you add support for that case?

2023-11-06 06:04 UTC, danstepanov commented on src/utilities/runCLI.ts
> +    success(`Ohkay!!, so you will build apks manually with gradle and xCode.`)
```suggestion
    success(`Sounds good 👍🏻`)
```

2023-11-06 06:04 UTC, danstepanov commented on src/utilities/runCLI.ts
> +  } else if (releaseWorkflowSetup === 'EAS') {
```suggestion
  } else {
```

2023-11-06 06:04 UTC, danstepanov commented on src/utilities/runCLI.ts
> +    success(`Great you chose to setup Codepush updates, but it's not supported right now`)
you can remove this

2023-11-08 12:21 UTC, frankcalise reviewed
So I don't know if it matters, but releasing (EAS Build) and OTA Updates (expo-updates package plus EAS update) can be considered two different things.

If you want to scale to CodePush later on as an option, you likely still want EAS Build configuration to happen (in fact I'd probably just support this no matter what the OTA strategy is), but not some of the other pieces such as:
- The `eas.json` just wouldn't need to know about the `channel` properties
- `app.json` wouldn't need the `updates` key

Both of those are pertaining to `expo-updates`

2023-11-09 05:42 UTC, AGRIT420 commented on src/templates/base/app.json.ejs
> +      "updates": {
This is following this doc , added  checkAutomatically option as well
[https://docs.expo.dev/versions/latest/config/app/#fallbacktocachetimeout](https://docs.expo.dev/versions/latest/config/app/#fallbacktocachetimeout)

2023-11-09 05:58 UTC, AGRIT420 commented on src/utilities/runCLI.ts
> +      error(`Need to install EAS cli to setup EAS release workflow`)
on the user's machine, I can't be added in dependencies, user has to login to their eas profile. It's equivalent to github-cli

2023-12-08 19:59 UTC, closed without merging

2023-12-08 19:59 UTC, danstepanov commented
EAS will be part of the paid starter, closing this for now